[deps]
GTFS = "55d01638-f41f-4520-a957-9ff9a0ad12ca"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
MissingLinks = "472ee5c9-fceb-493a-8c64-09683b8345c2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
