name = "PedTransitAccess"
uuid = "cb6b8e1c-cd33-46e5-81d1-801c2c09e7d5"
version = "0.0.1"
authors = ["Matt Bhagat-Conway <matt@indicatrix.org>"]

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GTFS = "55d01638-f41f-4520-a957-9ff9a0ad12ca"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LibSpatialIndex = "f19c2e90-9d16-5f2d-a2a7-af3fb29e4907"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
MissingLinks = "472ee5c9-fceb-493a-8c64-09683b8345c2"
OpenStreetMapPBF = "32359c53-f983-4442-b913-a1664815e12e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ArchGDAL = "0.10.8"
ArgParse = "1.2.0"
DataFrames = "1.7.0"
DataFramesMeta = "0.15"
DataStructures = "0.18.22"
GTFS = "1.0.0"
GeoDataFrames = "0.3.13"
LibGEOS = "0.9.4"
LibSpatialIndex = "0.2.1"
LinearAlgebra = "1.11.0"
MissingLinks = "0.2.1"
StatsBase = "0.34"
